#!/usr/bin/env bash

system_type=$(uname -s)

declare -a desired_packages

desired_packages+=(
    '7zip'
    'bat'
    'fzf'
    'git'
    'jq'
    'make'
    'plocate'
    'ranger'
    'ripgrep'
    'tmux'
    'zoxide'
    'zsh'
)

if [[ "Linux" == "$system_type" ]]; then
    os_id=$(sed -n -r -e 's/^ID_LIKE=(.+)/\1/p' /etc/os-release)
    [[ -z "$os_id" ]] && os_id=$(sed -n -r -e 's/^ID=(.+)/\1/p' /etc/os-release)
fi

if [[ -z "$XDG_SESSION_TYPE" ]]; then
    want_headless=1
else
    unset yn;
    while [[ -z $(echo $yn | grep -E '[yYnN]') ]]; do
        read -p "$* Is this a headless setup [y/n]: " -r yn
        case $yn in
            [Yy]*) want_headless=1;;
            [Nn]*);;
            *) ;;
        esac
    done
fi


unset yn;
while [[ -z $(echo $yn | grep -E '[yYnN]') ]]; do
    read -p "$* Do you want to install emacs [y/n]: " -r yn
    case $yn in
        [Yy]*) want_emacs=1;;
        [Nn]*);;
        *) ;;
    esac
done

if [[ ! $want_headless ]]; then
    case $XDG_SESSION_TYPE in
        wayland)
            desired_packages+=(
                'wl-clipboard'
            )
            ;;
        x11)
            desired_packages+=(
                'xclip'
            )
            ;;
    esac
fi

install_arch_packages() {
    desired_packages+=('imagemagick')
    if [[ $want_emacs == 1 ]]; then
        if [[ $want_headless ]]; then
            desired_packages+=('emacs-nox')
        else
            case $XDG_SESSION_TYPE in
                wayland) desired_packages+=('emacs-wayland') ;;
                x11) desired_packages+=('emacs') ;;
                *) desired_packages+=('emacs-nox') ;;
            esac
        fi
    fi

    # Install GUI packages
    if [[ ! $want_headless ]]; then
        if [[ -v WAYLAND_DISPLAY ]]; then
            # Wayland packages
            desired_packages+=()
        else
            # XOrg packages
            desired_packages+=()
        fi
    fi

    echo "${desired_packages[@]}"

    sudo pacman -S "${desired_packages[@]}"
}

install_fedora_packages() {
    desired_packages+=(
        'ImageMagick'
    )

    if [[ $want_emacs == 1 ]]; then
        desired_packages+=('pinentry-emacs' 'gnupg2-scdaemon')

        if [[ $want_headless ]]; then
            desired_packages+=('emacs-nw')
        else
            desired_packages+=('emacs')
        fi
    fi

    echo "${desired_packages[@]}"
    if [[ -x '/usr/bin/rpm-ostree' ]]; then
        # skip any packages taht are already installed,
        # rpm-ostree will stop if a requested package is already installed.
        packages_to_install=()
        for p in "${desired_packages[@]}"; do
            /usr/bin/rpm-ostree status | grep "$p" 2> /dev/null
            [[ $? ]] && packages_to_install+=("$p")
        done
        sudo rpm-ostree install "${packages_to_install[@]}"
    else
        sudo dnf install "${desired_packages[@]}"
    fi
}

install_debian_packages() {
    echo "${desired_packages[@]}"
    sudo apt install "${desired_packages[@]}"
}

case $os_id in
    arch)
        install_arch_packages
        ;;
    fedora)
        install_fedora_packages
        ;;
    debian)
        install_debian_packages
        ;;
    **)
esac
